#pragma once

#include "configuration.h"

#define KEYCODE_TYPE_NONE             (0x00)
#define KEYCODE_TYPE_STANDARD         (0x01)
#define KEYCODE_TYPE_MODIFIER         (0x02)
#define KEYCODE_TYPE_LAYOUT_HOLD      (0x03)
#define KEYCODE_TYPE_LAYOUT_PRESS     (0x04)
#define KEYCODE_TYPE_BACKLIGHT_MODE   (0x05)
#define KEYCODE_TYPE_BACKLIGHT_EFFECT (0x06)

#define KEYCODE_LAYOUT_1              (0x00)
#define KEYCODE_LAYOUT_2              (0x01)

#define KEYCODE_CODE_LEFT_CTRL        (0x01)
#define KEYCODE_CODE_LEFT_SHIFT       (0x02)
#define KEYCODE_CODE_LEFT_ALT         (0x04)
#define KEYCODE_CODE_LEFT_META        (0x08)
#define KEYCODE_CODE_RIGHT_CTRL       (0x10)
#define KEYCODE_CODE_RIGHT_SHIFT      (0x20)
#define KEYCODE_CODE_RIGHT_ALT        (0x40)
#define KEYCODE_CODE_RIGHT_META       (0x80)

#define KEYCODE_CODE_NONE             (0x00)

#define KEYCODE_CODE_A                (0x04)
#define KEYCODE_CODE_B                (0x05)
#define KEYCODE_CODE_C                (0x06)
#define KEYCODE_CODE_D                (0x07)
#define KEYCODE_CODE_E                (0x08)
#define KEYCODE_CODE_F                (0x09)
#define KEYCODE_CODE_G                (0x0A)
#define KEYCODE_CODE_H                (0x0B)
#define KEYCODE_CODE_I                (0x0C)
#define KEYCODE_CODE_J                (0x0D)
#define KEYCODE_CODE_K                (0x0E)
#define KEYCODE_CODE_L                (0x0F)
#define KEYCODE_CODE_M                (0x10)
#define KEYCODE_CODE_N                (0x11)
#define KEYCODE_CODE_O                (0x12)
#define KEYCODE_CODE_P                (0x13)
#define KEYCODE_CODE_Q                (0x14)
#define KEYCODE_CODE_R                (0x15)
#define KEYCODE_CODE_S                (0x16)
#define KEYCODE_CODE_T                (0x17)
#define KEYCODE_CODE_U                (0x18)
#define KEYCODE_CODE_V                (0x19)
#define KEYCODE_CODE_W                (0x1A)
#define KEYCODE_CODE_X                (0x1B)
#define KEYCODE_CODE_Y                (0x1C)
#define KEYCODE_CODE_Z                (0x1D)

#define KEYCODE_CODE_1                (0x1E)
#define KEYCODE_CODE_2                (0x1F)
#define KEYCODE_CODE_3                (0x20)
#define KEYCODE_CODE_4                (0x21)
#define KEYCODE_CODE_5                (0x22)
#define KEYCODE_CODE_6                (0x23)
#define KEYCODE_CODE_7                (0x24)
#define KEYCODE_CODE_8                (0x25)
#define KEYCODE_CODE_9                (0x26)
#define KEYCODE_CODE_0                (0x27)

#define KEYCODE_CODE_RETURN           (0x28)
#define KEYCODE_CODE_ESCAPE           (0x29)
#define KEYCODE_CODE_DELETE           (0x2A)
#define KEYCODE_CODE_TAB              (0x2B)
#define KEYCODE_CODE_SPACE            (0x2C)
#define KEYCODE_CODE_MINUS            (0x2D)
#define KEYCODE_CODE_EQUAL            (0x2E)
#define KEYCODE_CODE_BRACKET_LEFT     (0x2F)
#define KEYCODE_CODE_BRACKET_RIGHT    (0x30)
#define KEYCODE_CODE_BACKSLASH        (0x31)
#define KEYCODE_CODE_LATTICE          (0x32)
#define KEYCODE_CODE_SEMICOLON        (0x33)
#define KEYCODE_CODE_QUOTE            (0x34)
#define KEYCODE_CODE_GRAVE_ACCENT     (0x35)
#define KEYCODE_CODE_COMMA            (0x36)
#define KEYCODE_CODE_DOT              (0x37)
#define KEYCODE_CODE_SLASH            (0x38)
#define KEYCODE_CODE_CAPS_LOCK        (0x39)

#define KEYCODE_CODE_F_1              (0x3A)
#define KEYCODE_CODE_F_2              (0x3B)
#define KEYCODE_CODE_F_3              (0x3C)
#define KEYCODE_CODE_F_4              (0x3D)
#define KEYCODE_CODE_F_5              (0x3E)
#define KEYCODE_CODE_F_6              (0x3F)
#define KEYCODE_CODE_F_7              (0x40)
#define KEYCODE_CODE_F_8              (0x41)
#define KEYCODE_CODE_F_9              (0x42)
#define KEYCODE_CODE_F_10             (0x43)
#define KEYCODE_CODE_F_11             (0x44)
#define KEYCODE_CODE_F_12             (0x45)

#define KEYCODE_CODE_ARROW_RIGHT      (0x4F)
#define KEYCODE_CODE_ARROW_LEFT       (0x50)
#define KEYCODE_CODE_ARROW_DOWN       (0x51)
#define KEYCODE_CODE_ARROW_UP         (0x52)
