on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/battony/embedded:latest
    steps:
    - name: Clone
      run: git clone ${{ github.server_url }}/${{ github.repository }}.git

    - name: Checkout
      run: |
        cd $(basename ${{ github.repository }})
        git checkout ${{ github.ref }}

    - name: Build
      run: |
        cd $(basename ${{ github.repository }})
        make

    - name: Size
      run: |
        cd $(basename ${{ github.repository }})
        make size
